# Site settings
title: HiDream Team
SEOTitle: "梦 创 技术 团队"
email: hidream_tech@163.com
description: "打造nb的团队,nb的产品"
keyword: "前端 后端 ios iOS Android android 测试 运维 产品"
baseurl: ""
url: "www.hidream.tech"

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

excerpt : teaser
paginate : 9
paginate_path : ":num"

comments :
  provider : duoshuo
  duoshuo :
    short_name : hidream

baidu_analyze: d9da9bb820e87945d7717a17c257a67d
